# Generated by Django 4.2.2 on 2023-07-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDs', models.IntegerField()),
                ('location', models.CharField(max_length=80)),
                ('areacode', models.PositiveIntegerField()),
                ('mac_address', models.CharField(max_length=17)),
            ],
        ),
    ]
